--- #YAML:1.0
name:               Devel-Plumber
version:            0.3.4
abstract:           ~
author:
    - Greg Banks <gnb@fastmail.fm>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Devel::GDB:      0
    threads:         0
    Tree::Interval:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
